
import React from 'react';
import { 
  Zap, 
  Flame, 
  Dumbbell, 
  ShieldCheck, 
  Utensils, 
  TrendingDown, 
  Brain, 
  Activity,
  MinusCircle,
  Clock
} from 'lucide-react';
import { DietPhase, SubPhase, FoodItem, Language } from './types';

export const DIET_VIDEOS = {
  [DietPhase.LOW_CARB]: "https://www.youtube.com/embed/RkGfE_7Xw5M",
  [DietPhase.KETOGENIC]: "https://www.youtube.com/embed/RkGfE_7Xw5M",
  [DietPhase.CARNIVORE]: "https://www.youtube.com/embed/RkGfE_7Xw5M",
};

export const TRANSLATIONS = {
  pt: {
    app_title: "Caminho Metabólico",
    phases: {
      [DietPhase.LOW_CARB]: "Low Carb",
      [DietPhase.KETOGENIC]: "Cetogênica",
      [DietPhase.CARNIVORE]: "Carnívora",
    },
    subPhases: {
      [SubPhase.START]: "Início",
      [SubPhase.ADAPTATION]: "Adaptação",
      [SubPhase.TRANSITION]: "Transição",
      [SubPhase.RESULTS]: "Resultados",
    },
    objectives: {
      [DietPhase.LOW_CARB]: "Reduzir a dependência de açúcar e carboidratos.",
      [DietPhase.KETOGENIC]: "Adaptar o corpo a usar gordura como principal fonte de energia.",
      [DietPhase.CARNIVORE]: "Fase final com foco em produtos de origem animal.",
    },
    ui: {
      current_phase: "Fase Atual",
      weekly_goals: "Metas da Semana",
      perceived_benefits: "Benefícios Percebidos",
      main_objectives: "Objetivos Principais",
      how_it_works: "Como Funciona",
      carb_calc: "Calculadora de Carbos",
      limit_daily: "Limite diário",
      consumed: "Consumido",
      register_food: "Registrar Alimento",
      search_placeholder: "Pesquisar alimento...",
      game_tip: "DICA DE JOGO",
      consistency_bonus: "Mantenha abaixo do limite hoje para ganhar o bônus de consistência!",
      nav_diet: "Dieta",
      nav_explore: "Explorar",
      nav_progress: "Progresso",
      nav_profile: "Perfil",
      start_now: "Começar agora",
      talk_doctor: "Falar com um médico",
      swipe_continue: "Deslize para continuar",
      explore_protocol: "Explorar o Protocolo",
      problem_header: "FASE 1: LOW CARB",
      problem_text: "Reduza a dependência de açúcar e carboidratos.",
      proposal_header: "A PROPOSTA",
      proposal_text: "Menos estímulos.\nMais resultado.",
      action_text: "Seu corpo sabe o que fazer. Você só precisa parar de atrapalhar.",
      not_fad_header: "NÃO É MODA",
      not_fad_text: "A dieta Low Carb não é tendência. É estratégia metabólica.",
      medical_supervision: "SUPERVISÃO MÉDICA",
      tap_clean: "Toque para avançar e descobrir o poder do low carb.",
      evolution_soon: "Tela de Evolução em breve...",
      profile_metabolic: "Seu Perfil Metabólico...",
      sugar: "Sem Açúcar",
      processed: "Limite 50g",
      inflammation: "Novos Hábitos",
      lang_selector: "Idioma",
      steak_alt: "Ícone de Carne",
      my_goals: "MINHAS METAS",
      settings: "CONFIGURAÇÕES",
      weight_goal: "META DE PESO",
      current_weight_label: "Peso Atual (kg)",
      target_weight_label: "Meta de Peso (kg)",
      water_goal: "META DE ÁGUA",
      water_goal_label: "Meta de Água (Litros/dia)",
      missing: "Faltam",
      personal_data: "Dados Pessoais",
      privacy: "Privacidade",
      notifications: "Notificações",
      support: "Suporte",
      sign_out: "Sair da Conta",
      back: "Voltar",
      name_label: "Nome Completo",
      email_label: "E-mail",
      phone_label: "Telefone",
      password_label: "Senha",
      save_button: "Salvar Alterações",
      edit_profile: "Editar Dados Pessoais",
      edit_goals: "Editar Metas",
      benefit_tip: "Benefício Metabólico",
      congrats: "Parabéns!",
      ready_next_phase: "Você completou todos os requisitos! Está pronto para a próxima fase?",
      advance_now: "Avançar de Fase",
      no_notifications: "Nenhuma notificação por enquanto.",
      food_table: "Tabela Nutricional",
      what_is: "O que é a dieta",
      category_all: "Todos",
      category_protein: "Proteínas",
      category_vegetable: "Vegetais",
      category_fruit: "Frutas",
      category_grain: "Grãos/Carbos",
      category_dairy: "Laticínios",
      task_done_toast: "Meta atingida! +10 XP Metabólico",
      locked_phase_title: "Acesso Bloqueado",
      locked_phase_message: "Ainda não está na hora ou não está liberado para você ainda. Foque na sua fase atual!",
      locked_phase_btn: "Entendido",
      nutrition_details: "Detalhes Nutricionais",
      calories: "Calorias",
      protein: "Proteína",
      fat: "Gordura",
      add_to_today: "Adicionar à ingestão de hoje",
      portion_100g: "Por 100g",
      portion_cup: "Por Xícara",
      portion_unit: "Por Unidade",
      added_toast: "Alimento adicionado com sucesso!",
    },
    tasks: {
      t1: "Retirar açúcar do café",
      t2: "Comprar carnes da semana",
      t3: "Caminhada de 20 min",
      t4: "Beber 3L de água",
    },
    taskBenefits: {
      t1: "Reduz picos de insulina e facilita a entrada em cetose.",
      t2: "Garante saciedade e evita o consumo de ultraprocessados.",
      t3: "Melhora a sensibilidade à insulina e a queima de gordura.",
      t4: "Auxilia na eliminação de toxinas e reduz a retenção hídrica.",
    },
    benefits: [
      { label: "Menos fome" },
      { label: "Menos estufamento" },
      { label: "Mais foco" },
      { label: "Mais disposição" },
      { label: "Melhor controle do peso" },
    ],
    main_obj: [
      { title: "Reduzir inflamação" },
      { title: "Regular o metabolismo" },
      { title: "Preservar massa magra" },
      { title: "Aumentar energia", description: "Aumente a vitalidade diária com alimentos densos em nutrientes." },
    ]
  },
  en: {
    app_title: "Metabolic Path",
    phases: {
      [DietPhase.LOW_CARB]: "Low Carb",
      [DietPhase.KETOGENIC]: "Ketogenic",
      [DietPhase.CARNIVORE]: "Carnivore",
    },
    subPhases: {
      [SubPhase.START]: "Start",
      [SubPhase.ADAPTATION]: "Adaptation",
      [SubPhase.TRANSITION]: "Transition",
      [SubPhase.RESULTS]: "Results",
    },
    objectives: {
      [DietPhase.LOW_CARB]: "Reduce dependence on sugar and carbohydrates.",
      [DietPhase.KETOGENIC]: "Adapt the body to use fat as the primary energy source.",
      [DietPhase.CARNIVORE]: "Final phase focusing on animal-sourced products.",
    },
    ui: {
      current_phase: "Current Phase",
      weekly_goals: "Weekly Goals",
      perceived_benefits: "Perceived Benefits",
      main_objectives: "Main Objectives",
      how_it_works: "How it Works",
      carb_calc: "Carb Calculator",
      limit_daily: "Daily limit",
      consumed: "Consumed",
      register_food: "Register Food",
      search_placeholder: "Search food...",
      game_tip: "GAME TIP",
      consistency_bonus: "Keep below the limit today to earn the consistency bonus!",
      nav_diet: "Diet",
      nav_explore: "Explore",
      nav_progress: "Progress",
      nav_profile: "Profile",
      start_now: "Start Now",
      talk_doctor: "Talk to a Doctor",
      swipe_continue: "Swipe to continue",
      explore_protocol: "Explore Protocol",
      problem_header: "PHASE 1: LOW CARB",
      problem_text: "Reduce dependence on sugar and carbohydrates.",
      proposal_header: "THE PROPOSAL",
      proposal_text: "Less stimuli.\nMore results.",
      action_text: "Your body knows what to do. You just need to stop hindering it.",
      not_fad_header: "NOT A FAD",
      not_fad_text: "The Low Carb diet isn't a trend. It's a metabolic strategy.",
      medical_supervision: "MEDICAL SUPERVISION",
      tap_clean: "Tap to advance and discover the power of low carb.",
      evolution_soon: "Evolution screen coming soon...",
      profile_metabolic: "Your Metabolic Profile...",
      sugar: "No Sugar",
      processed: "50g Limit",
      inflammation: "New Habits",
      lang_selector: "Language",
      steak_alt: "Steak Icon",
      my_goals: "MY GOALS",
      settings: "SETTINGS",
      weight_goal: "WEIGHT GOAL",
      current_weight_label: "Current Weight (kg)",
      target_weight_label: "Target Weight (kg)",
      water_goal: "WATER GOAL",
      water_goal_label: "Water Goal (Liters/day)",
      missing: "Missing",
      personal_data: "Personal Data",
      privacy: "Privacy",
      notifications: "Notifications",
      support: "Support",
      sign_out: "Sign Out",
      back: "Back",
      name_label: "Full Name",
      email_label: "E-mail",
      phone_label: "Phone",
      password_label: "Password",
      save_button: "Save Changes",
      edit_profile: "Edit Personal Data",
      edit_goals: "Edit Goals",
      benefit_tip: "Metabolic Benefit",
      congrats: "Congratulations!",
      ready_next_phase: "You have completed all requirements! Ready for the next phase?",
      advance_now: "Advance Phase",
      no_notifications: "No notifications yet.",
      food_table: "Nutrition Table",
      what_is: "What is the diet",
      category_all: "All",
      category_protein: "Proteins",
      category_vegetable: "Vegetables",
      category_fruit: "Fruits",
      category_grain: "Grains/Carbs",
      category_dairy: "Dairy",
      task_done_toast: "Goal achieved! +10 Metabolic XP",
      locked_phase_title: "Access Locked",
      locked_phase_message: "It's not time yet or it's not released for you yet. Focus on your current phase!",
      locked_phase_btn: "Understood",
      nutrition_details: "Nutrition Details",
      calories: "Calories",
      protein: "Protein",
      fat: "Fat",
      add_to_today: "Add to today's intake",
      portion_100g: "Per 100g",
      portion_cup: "Per Cup",
      portion_unit: "Per Unit",
      added_toast: "Food successfully added!",
    },
    tasks: {
      t1: "Remove sugar from coffee",
      t2: "Buy meat for the week",
      t3: "20 min walk",
      t4: "Drink 3L of water",
    },
    taskBenefits: {
      t1: "Reduces insulin spikes and helps you enter ketosis faster.",
      t2: "Ensures satiety and prevents ultra-processed cravings.",
      t3: "Improves insulin sensitivity and metabolic rate.",
      t4: "Helps flush out toxins and reduces water retention.",
    },
    benefits: [
      { label: "Less hunger" },
      { label: "Less bloating" },
      { label: "Better focus" },
      { label: "More energy" },
      { label: "Weight control" },
    ],
    main_obj: [
      { title: "Reduce inflammation" },
      { title: "Regulate metabolism" },
      { title: "Preserve lean mass" },
      { title: "Increase energy", description: "Boost daily vitality with nutrient-dense animal foods." },
    ]
  }
};

export const DIET_CONFIG = {
  [DietPhase.LOW_CARB]: { limit: 50, color: 'red-500' },
  [DietPhase.KETOGENIC]: { limit: 20, color: 'orange-500' },
  [DietPhase.CARNIVORE]: { limit: 5, color: 'red-700' },
};

export const BENEFIT_ICONS = [
  <Utensils className="text-red-500" size={32} />,
  <Activity className="text-red-500" size={32} />,
  <Brain className="text-red-500" size={32} />,
  <Zap className="text-red-500" size={32} />,
  <TrendingDown className="text-red-500" size={32} />,
];

export const OBJECTIVE_ICONS = [
  <Flame className="text-red-500" />,
  <Activity className="text-red-500" />,
  <Dumbbell className="text-red-500" />,
  <Zap className="text-red-500" />,
];

export const FOOD_DATABASE: FoodItem[] = [
  // Proteins
  { name: { pt: 'Bife Bovino', en: 'Beef Steak' }, carbs: 0, calories: 250, protein: 26, fat: 15, category: 'protein', servingWeights: { unit: 150 } },
  { name: { pt: 'Peito de Frango', en: 'Chicken Breast' }, carbs: 0, calories: 165, protein: 31, fat: 3.6, category: 'protein', servingWeights: { unit: 120 } },
  { name: { pt: 'Ovo Inteiro', en: 'Whole Egg' }, carbs: 0.6, calories: 143, protein: 12.6, fat: 9.5, category: 'protein', servingWeights: { unit: 50 } },
  { name: { pt: 'Salmão', en: 'Salmon' }, carbs: 0, calories: 208, protein: 20, fat: 13, category: 'protein', servingWeights: { unit: 150 } },
  { name: { pt: 'Panceta', en: 'Pork Belly' }, carbs: 0, calories: 518, protein: 9, fat: 53, category: 'protein', servingWeights: { unit: 100 } },
  
  // Vegetables (Low Carb)
  { name: { pt: 'Brócolis', en: 'Broccoli' }, carbs: 7, calories: 34, protein: 2.8, fat: 0.4, category: 'vegetable', servingWeights: { cup: 90 } },
  { name: { pt: 'Espinafre', en: 'Spinach' }, carbs: 3.6, calories: 23, protein: 2.9, fat: 0.4, category: 'vegetable', servingWeights: { cup: 30 } },
  { name: { pt: 'Abobrinha', en: 'Zucchini' }, carbs: 3.1, calories: 17, protein: 1.2, fat: 0.3, category: 'vegetable', servingWeights: { cup: 120, unit: 200 } },
  { name: { pt: 'Couve-flor', en: 'Cauliflower' }, carbs: 5, calories: 25, protein: 1.9, fat: 0.3, category: 'vegetable', servingWeights: { cup: 100 } },
  
  // Fruits (Low GI)
  { name: { pt: 'Abacate', en: 'Avocado' }, carbs: 8.5, calories: 160, protein: 2, fat: 15, category: 'fruit', servingWeights: { unit: 200, cup: 150 } },
  { name: { pt: 'Morango', en: 'Strawberry' }, carbs: 7.7, calories: 32, protein: 0.7, fat: 0.3, category: 'fruit', servingWeights: { cup: 150, unit: 15 } },
  { name: { pt: 'Mirtilo', en: 'Blueberry' }, carbs: 14, calories: 57, protein: 0.7, fat: 0.3, category: 'fruit', servingWeights: { cup: 150 } },
  
  // Dairy / Fats
  { name: { pt: 'Manteiga', en: 'Butter' }, carbs: 0.1, calories: 717, protein: 0.9, fat: 81, category: 'fat' },
  { name: { pt: 'Azeite de Oliva', en: 'Olive Oil' }, carbs: 0, calories: 884, protein: 0, fat: 100, category: 'fat' },
  { name: { pt: 'Queijo Cheddar', en: 'Cheddar Cheese' }, carbs: 1.3, calories: 403, protein: 25, fat: 33, category: 'dairy', servingWeights: { cup: 130 } },
  { name: { pt: 'Iogurte Grego', en: 'Greek Yogurt' }, carbs: 3.6, calories: 59, protein: 10, fat: 0.4, category: 'dairy', servingWeights: { cup: 240 } },
  
  // Grains / High Carbs
  { name: { pt: 'Arroz Branco', en: 'White Rice' }, carbs: 28, calories: 130, protein: 2.7, fat: 0.3, category: 'grain', servingWeights: { cup: 160 } },
  { name: { pt: 'Pão Francês', en: 'Bread' }, carbs: 45, calories: 265, protein: 9, fat: 3, category: 'grain', servingWeights: { unit: 50 } },
  { name: { pt: 'Macarrão', en: 'Pasta' }, carbs: 31, calories: 158, protein: 5.8, fat: 0.9, category: 'grain', servingWeights: { cup: 140 } },
];
